name: Feature Request
description: Suggest an idea to improve this project.
title: "[Feature]: Describe the feature"
labels: [enhancement]
assignees: [ms2176]
body:
  - type: textarea
    id: problem_description
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is."
      placeholder: "Describe the problem here..."

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Describe your proposed solution here..."
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: "Describe alternatives you've considered"
      description: "Any alternative solutions or features you've considered."
      placeholder: "Describe alternatives here..."

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Include any additional information here..."
