name: General Issue Form
description: "Use this form to submit an issue that doesn't fit into any of the predefined categories."
title: "General Issue Report"
labels: []
assignees: [ms2176]

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the issue or suggestion in detail."
      placeholder: "Provide a clear and concise description..."

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any other relevant information or context."
      placeholder: "Include any additional information here..."

  - type: input
    id: optional_fields
    attributes:
      label: "Additional Information (Optional)"
      description: "Provide any other optional information that might be helpful."
      placeholder: "Optional details here..."
